// angular/src/app/about/about.component.ts
import { Component, OnInit } from '@angular/core';
import { Leader } from '../shared/leader';
import { LEADERS } from '../shared/leaders';
import { LeaderService } from '../services/leader.service';
import { flyInOut, expand } from '../animations/app.animation';
import {baseURL} from '../shared/baseurl';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.scss'],
  // tslint:disable-next-line:use-host-property-decorator
  host: {
    '[@flyInOut]': 'true',
    'style': 'display: block;'
  },
  animations: [
    flyInOut(),
    expand()
  ]
})
export class AboutComponent implements OnInit {
  leader: Leader;
  leaders: Leader[];
  dataURL : string;
  errLeaderMess: string;

  constructor(private leaderService: LeaderService) { }

  ngOnInit(): void {
    this.dataURL = baseURL;
    //this.leader = this.leaderService.getFeaturedLeader();
    //this.leaders = this.leaderService.getLeaders();
    // this.leaderService.getFeaturedLeader().then(leader => this.leader = leader);
    // this.leaderService.getLeaders().then(leaders => this.leaders = leaders);
    //this.leaderService.getFeaturedLeader().subscribe(leader => this.leader = leader, errmess => this.errLeaderMess = <any>errmess);
    this.leaderService.getLeaders().subscribe(leaders => this.leaders = leaders, errmess => this.errLeaderMess = <any>errmess);
  }

}

<div class="container"
  fxLayout="column"
  fxLayoutGap="10px">

  <div fxFlex>
    <div>
        <h3>About Us</h3>
        <hr>
    </div>
  </div>

  <div fxFlex>
    <div fxLayout="column" fxLayout.gt-sm="row">
      <div fxFlex="70">
        <h2>Our History</h2>
        <p>Started in 2010, Ristorante con Fusion quickly established itself as a culinary icon par excellence in Hong Kong. With its unique brand of world fusion cuisine that can be found nowhere else, it enjoys patronage from the A-list clientele in Hong Kong.  Featuring four of the best three-star Michelin chefs in the world, you never know what will arrive on your plate the next time you visit us.</p>
        <p>The restaurant traces its humble beginnings to <em>The Frying Pan</em>, a successful chain started by our CEO, Mr. Peter Pan, that featured for the first time the world's best cuisines in a pan.</p>
      </div>
      <div fxFlex="30">
        <mat-card>
          <mat-card-header>
            <mat-card-title>
            <h2>Facts At a Glance</h2>
            </mat-card-title>
          </mat-card-header>
          <mat-card-content>
            <dl>
              <dt>Started</dt>
              <dd>3 Feb. 2013</dd>
              <dt>Major Stake Holder</dt>
              <dd>HK Fine Foods Inc.</dd>
              <dt>Last Year's Turnover</dt>
              <dd>$1,250,375</dd>
              <dt>Employees</dt>
              <dd>40</dd>
            </dl>
          </mat-card-content>
        </mat-card>
      </div>
    </div>
  </div>
  
  <div fxFlex>
    <mat-card>
      <blockquote>
        <h3>You better cut the pizza in four pieces because
            I'm not hungry enough to eat six.</h3>
        <footer>-- Yogi Berra,
          <cite>The Wit and Wisdom of Yogi Berra,
            P. Pepe, Diversion Books, 2014</cite>
        </footer>
      </blockquote>
    </mat-card>
  </div>


  <div fxFlex>
    <h2>Corporate Leadership</h2>
    <div class="container"
        fxLayout="column wrap"
        fxLayoutGap="30px" *ngIf="leaders" [@expand]>
            <mat-list>
                <mat-list-item fxLayout="column" style="height: 150px;" *ngFor="let leader of leaders">
                  <img style="border-radius: 50%" [src]="(dataURL+leader.image).replace('assets', '')" alt={{leader.name}} width="60px">
                  <div>
                    <h4 mat-line> {{leader.name}} {{leader.abbr}} </h4>
                    <p mat-line>{{leader.designation}}</p>
                    <p mat-line> {{leader.description}}</p>
                  </div> 
                </mat-list-item>
            </mat-list>
      </div>
      <div [hidden]="leaders || errLeaderMess">
        <mat-spinner></mat-spinner><h4>Loading . . . Please Wait</h4>
      </div>
      <div fxFlex *ngIf="errLeaderMess">
        <h2>Error</h2>
        <h4>{{errLeaderMess}}</h4>
      </div>
  </div>
</div>

// react/src/components/AboutComponent.js
import React from 'react';
import { Breadcrumb, BreadcrumbItem, Card, CardBody, CardHeader, Media } from 'reactstrap';
import { Link } from 'react-router-dom';
import { Loading } from './LoadingComponent';
import { baseUrl } from '../shared/baseUrl';

function RenderLeaders({props}) {
    if (props.leaders.isLoading) {
        return(
            <div className="container">
                <div className="row">            
                    <Loading />
                </div>
            </div>
        );
    }
    else if (props.leaders.errMess) {
        return(
            <div className="container">
                <div className="row"> 
                    <div className="col-12">
                        <h4>{props.leaders.errMess}</h4>
                    </div>
                </div>
            </div>
        );
    } else {
        const leaders = props.leaders.leaders.map((leader) => {
            return (
                <Media tag="li" className="list-unstyled mt-3">
                    <div className="container row" >
                        <div className="col-4">
                            <Media object src={baseUrl + leader.image} alt={leader.name} width="90px"/>
                        </div>
                        <div className="col-8">
                            <Media heading>{leader.name}</Media>
                            <p>{leader.designation}</p>
                            <p>{leader.description}</p>
                        </div>
                    </div>
                </Media>
            );
        });
        return (
            <div className="col-12">
                <Media list>
                    { leaders }
                </Media>
            </div>
        );
    }
}

function About(props) {

    return(
        <div className="container">
            <div className="row">
                <Breadcrumb>
                    <BreadcrumbItem><Link to="/home">Home</Link></BreadcrumbItem>
                    <BreadcrumbItem active>About Us</BreadcrumbItem>
                </Breadcrumb>
                <div className="col-12">
                    <h3>About Us</h3>
                    <hr />
                </div>                
            </div>
            <div className="row row-content">
                <div className="col-12 col-md-6">
                    <h2>Our History</h2>
                    <p>Started in 2010, Ristorante con Fusion quickly established itself as a culinary icon par excellence in Hong Kong. With its unique brand of world fusion cuisine that can be found nowhere else, it enjoys patronage from the A-list clientele in Hong Kong.  Featuring four of the best three-star Michelin chefs in the world, you never know what will arrive on your plate the next time you visit us.</p>
                    <p>The restaurant traces its humble beginnings to <em>The Frying Pan</em>, a successful chain started by our CEO, Mr. Peter Pan, that featured for the first time the world's best cuisines in a pan.</p>
                </div>
                <div className="col-12 col-md-5">
                    <Card>
                        <CardHeader className="bg-primary text-white">Facts At a Glance</CardHeader>
                        <CardBody>
                            <dl className="row p-1">
                                <dt className="col-6">Started</dt>
                                <dd className="col-6">3 Feb. 2013</dd>
                                <dt className="col-6">Major Stake Holder</dt>
                                <dd className="col-6">HK Fine Foods Inc.</dd>
                                <dt className="col-6">Last Year's Turnover</dt>
                                <dd className="col-6">$1,250,375</dd>
                                <dt className="col-6">Employees</dt>
                                <dd className="col-6">40</dd>
                            </dl>
                        </CardBody>
                    </Card>
                </div>
                <div className="col-12">
                    <Card>
                        <CardBody className="bg-faded">
                            <blockquote className="blockquote">
                                <p className="mb-0">You better cut the pizza in four pieces because
                                    I'm not hungry enough to eat six.</p>
                                <footer className="blockquote-footer mt-1">Yogi Berra,
                                <cite title="Source Title">The Wit and Wisdom of Yogi Berra,
                                    P. Pepe, Diversion Books, 2014</cite>
                                </footer>
                            </blockquote>
                        </CardBody>
                    </Card>
                </div>
            </div>
            <div className="row row-content">
                <div className="col-12">
                    <h2>Corporate Leadership</h2>
                </div>
                <RenderLeaders props={props}/>
            </div>
        </div>
    );
}

export default About;
